# Default to the local Devnet. Can set chain id for some hard-coded chain config
#  - i.e OP Mainnet, OP Goerli, Base, Base Goerli, Zora, Zora Goerli, etc
[chain]
preset = 901

### ChainConfiguration. Uncomment to set desired L1 & L2 config
##  l1-polling-interval = 0
##  l1-header-buffer-size = 0
##  l1-confirmation-depth = 0
##  l1-starting-height = 0
##  
##  l2-polling-interval = 0
##  l2-header-buffer-size = 0
##  l2-confirmation-depth = 0
###

[rpcs]
l1-rpc = "http://127.0.0.1:8545"
l2-rpc = "http://127.0.0.1:9545"

[db]
host = "127.0.0.1"
port = 5432
user = "db_username"
password = "db_password"
name = "db_name"

[http]
host = "127.0.0.1"
port = 8080
timeout = 10

[metrics]
host = "127.0.0.1"
port = 7300

