# Default to the local Devnet Preset
# See /config/presets.go for available preset configurations
#  - i.e OP Mainnet, OP Goerli, Base, Base Goerli, Zora, Zora Goerli, etc
[chain]
preset = 901

l1-polling-interval = 5000
l2-polling-interval = 5000

l1-header-buffer-size = 1000
l2-header-buffer-size = 1000

### For the devnet, we'll use a confirmation depth of 0.
### However important to set for live networks to avoid
### getting into a stuck state due to a reorg
###
# l1-confirmation-depth = 10
# l2-confirmation-depth = 75  (rough 10 L1 block equivalent)
###
###

[rpcs]
l1-rpc = "${INDEXER_L1_RPC_URL}"
l2-rpc = "${INDEXER_L2_RPC_URL}"

[db]
host = "${DB_HOST}"
port = ${DB_PORT}
user = "${DB_USER}"
password = "${DB_PWD}"
name = "${DB_NAME}"

[http]
host = "0.0.0.0"
port = 8100
timeout = 10

[metrics]
host = "0.0.0.0"
port = 7300
